services:
  chapterise:
    build: .
    image: chapterise:local
    init: true
    ports:
      - "8765:8765"
    volumes:
      - projects:/data
      - models:/models

volumes:
  projects:
  models:
